FROM openliberty/open-liberty:microProfile2-java8-openj9
# OpenJ9 0.12.1
# OpenJDK 8u202-b08
# Open Liberty 18.0.0.4
# MicroProfile 2.1 

COPY java-jee/liberty/server.xml /config/

ADD java-jee/target/function.war /config/